### ISSUE TITLE
why do we need to sample a dataframe to see the confidence intervals?

### ISSUE THREAD

**Issue by solegalli** [DanaJomar/PyALE#21]
If I execute the code in[ this example](https://htmlpreview.github.io/?https://github.com/DanaJomar/PyALE/blob/master/examples/Examples.html), I obtain what's shown there. 

But if I replace in cell 13 `X_sample` by `X[features]`, then I do not see the confidence intervals any more. Is this a bug? or is this intentional?

**Comment by DanaJomar** [comment]
Indeed they won't be clearly seen, however they do exists but they are tight, that was why I used a sample, because my goal with this example was to show the confidence interval, but the data generated a very small interval, which was not easy to see.

You can see this better if you look at the values of the ALE effects and the interval
![image](https://github.com/DanaJomar/PyALE/assets/42438529/016b3e7c-d893-493b-b1fe-cdf651845296)

**Comment by solegalli** [comment]
Thanks!
